M5 (pen up)
G4 P1 (wait a ms so the PWM changes can take action)
%
(Header)
(Generated by gcodetools from Inkscape.)
(Using default header. To add your own header create file "header" in the output dir.)
(Header end.)
G21 (All units in mm)

(Start cutting path id: rect10)
(Change tool to Default tool)

G00 Z5.000000
G00 X0.000000 Y100.000000

M3 (pen down)
G4 P1 (wait a ms so the PWM changes can take action)
G01 X100.000000 Y100.000000 Z-0.125000 F400.000000
G01 X100.000000 Y0.000000 Z-0.125000
G01 X0.000000 Y0.000000 Z-0.125000
G01 X0.000000 Y100.000000 Z-0.125000
M5 (pen up)
G4 P1 (wait a ms so the PWM changes can take action)

(End cutting path id: rect10)


(Footer)
G00 X0.0000 Y0.0000
M2
(Using default footer. To add your own footer create file "footer" in the output dir.)
(end)
%
