[package]
name = "grbl-servo-worker"
version = "0.1.0"
authors = ["hargoniX <hargonix@gmail.com>"]
edition = "2018"

[dependencies]
amqp = {version = "0.1.2", default-features = false}
serialport = "3.2.0"