[package]
name = "grbl-servo-server"
version = "0.1.0"
authors = ["hargoniX <hargonix@gmail.com>"]
edition = "2018"

[dependencies]
quicli = "0.4"
rocket = "0.4"
structopt = "0.2"
serde_derive = "1.0"
serde = "1.0"
rocket_contrib = "0.4"
amqp = {version = "0.1.2", default-features = false}